# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-oracle

# Set the working directory in the container
WORKDIR /app

# Copy the project's JAR files into the container at /app
COPY ../build/libs /app/

# Make port 9090 available to the world outside this container
EXPOSE 9090

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/delivery-0.0.1-SNAPSHOT.jar"]
